package httpapi

// D5 — the authorization request is not bound to the browser that created it.
//
// THE ATTACK. `/oidc/login/{requestID}` completes an authorization request for
// whoever presents a live session cookie, with no check that this browser is the
// one that started the flow. The request id is a bearer capability: it is a uuid
// in a URL, it is handed to the browser that began the flow, and the ONLY
// property standing between "the browser that began this flow" and "any browser
// with a session for the same user" is that the id happens to be unguessable.
//
// So an attacker who can get a signed-in user's browser to navigate to a login
// URL THEY chose — a link in chat, a page they control, an image, anything that
// issues a top-level GET — has that user's browser complete the attacker's
// authorization request. The attacker registered the client, the attacker holds
// the client secret, the attacker holds the PKCE verifier, and the redirect
// carries a `code` to a redirect_uri on a host the attacker registered. They
// exchange it and receive an id_token and an access_token whose `sub` is the
// victim.
//
// This is login CSRF / session fixation against the authorization endpoint. The
// `state` parameter is generated BY THE CLIENT and protects the CLIENT's own
// callback; it does nothing here, because the attacker is the client and knows
// their own state. `prompt=login` would force interaction, and `max_age` is
// refused outright (handleOIDCAuthorize), which removes the client's one
// remaining lever.
//
// THE FIX is that the browser which is about to be redirected into the flow must
// be able to prove it is the one the flow was handed to. The same
// `__Host-`-prefixed, per-request-id cookie the interaction already uses is that
// proof: set it when the login step begins OR at the authorize step, and require
// it before any completion — including the silent one.
//
// NO SECRET IS PRINTED. The fixture mints a real client secret and real codes;
// nothing here renders one. Assertions are on status codes, on the presence of a
// `code`, and on the `sub` of a verified token.
//
// # THIS FILE SURVIVED THE MOVE OF THE FORM OUT, AND THE REASON MATTERS
//
// The obvious worry is that a login form on another origin makes the attack
// easier: the attacker's page is not even needed, the victim is simply sent to a
// page that asks for a password. It does not, and the test below is the proof —
// the answer to the attacker's link is still a 403 for a signed-in browser, because
// the flow cookie is a `SameSite=Lax` cookie and a top-level GET is the ONE case
// Lax still permits, and because a Lax cookie is a cookie the attacker's origin
// cannot WRITE. The two interaction cookies did have to become `SameSite=None` to
// survive the cross-site POST (see oidcInteractionSameSite), and they are not the
// ones this defence rests on.

import (
	"net/http"
	"net/url"
	"strings"
	"testing"

	"github.com/cafaye/identity/internal/oidc"
	"github.com/cafaye/identity/internal/platform/dbtest"
)

// oidcFlowBindingFixture is an oidcFixture plus a second browser.
//
// The point of the attack is that TWO browsers are involved and the service
// cannot tell them apart, so a test that drives one jar proves nothing. The
// attacker's browser is `attackerJar`; the victim's session lives in `f.jar`.
type oidcFlowBindingFixture struct {
	*oidcFixture
	// attackerJar is a browser that has NO session cookie. It is what an
	// attacker's browser looks like: it started the flow and is not signed in.
	attackerJar *cookieJar
}

// authorizeAsAnUnauthenticatedBrowser drives GET /oidc/authorize from a browser
// that holds no session, which is the attacker's position: they register a
// client, they start a flow, and they never authenticate.
func (f *oidcFlowBindingFixture) authorizeAnonymous(t *testing.T, client registered, challenge, state, nonce string) string {
	t.Helper()

	query := url.Values{
		"client_id":             []string{client.ClientID},
		"redirect_uri":          []string{oidcTestRedirect},
		"response_type":         []string{"code"},
		"scope":                 []string{"openid email profile accounts"},
		"state":                 []string{state},
		"nonce":                 []string{nonce},
		"code_challenge":        []string{challenge},
		"code_challenge_method": []string{"S256"},
	}

	req := newRequestNoCookie(http.MethodGet, oidc.PathAuthorize+"?"+query.Encode())
	rec := newResponse(serveRecorder(f.handler, req))
	if rec.Code != http.StatusFound {
		t.Fatalf("GET /oidc/authorize = %d, want 302; body: %s", rec.Code, rec.Body)
	}

	location := rec.Header().Get("Location")
	if !hasPrefixPath(location, oidc.PathLogin+"/") {
		t.Fatalf("the browser was sent to %q, want the login page", location)
	}
	return location
}

// hasPrefixPath is strings.HasPrefix, named so this file does not import
// strings for one call.
func hasPrefixPath(got, prefix string) bool {
	return len(got) >= len(prefix) && got[:len(prefix)] == prefix
}

// RED PROOF — the authorization request is spendable by a browser that did not
// start it.
//
// THE ASSERTION. The victim's browser holds a live session and NOTHING ELSE —
// no flow cookie, because the victim's browser never began this flow. It follows
// the attacker's login URL.
//
// Today that is answered with a 302 carrying a `code` to the attacker's
// registered redirect_uri. The fix answers it with something that is not a code.
//
// THE TWO HONEST ANSWERS ARE NOW SPELLED OUT rather than logged, because the
// third one this test used to tolerate is gone and its disappearance is worth
// asserting: with a form on another origin, "200 with a form" is no longer a
// possible answer, and a handler that rendered a page would be a violation of the
// thing this packet is about as well as a security defect. So:
//
//	403                    a problem document: this browser cannot prove it started
//	                        this flow. THE EXPECTED ANSWER for a signed-in browser.
//	302 to the login UI    the victim is signed OUT, so there is nothing to
//	                        complete silently and the interaction has to start.
//	302 to the product     the silent path, which requires a flow cookie this
//	                        browser does not have. NEVER acceptable.
func TestAnAuthorizationRequestIsNotSpendableByABrowserThatDidNotStartIt(t *testing.T) {
	t.Parallel()

	f := &oidcFlowBindingFixture{oidcFixture: newOIDCFixture(t), attackerJar: &cookieJar{}}

	// The attacker registers their own client. Owner-gated on an account they
	// own, which any registered user has one of.
	client := f.registerClient(t)

	// The attacker starts the flow from a browser with NO session. They get the
	// login URL for a request id only they were given.
	_, challenge := codeVerifier(t)
	attackerLoginURL := f.authorizeAnonymous(t, client, challenge, "state-attacker", "nonce-attacker")

	// The VICTIM's browser. `f.jar` already holds a live session for the same
	// user the fixture registered (newOIDCFixture signs them in), and it holds no
	// flow cookie, because this browser never began this flow. The attacker's jar
	// is discarded entirely.
	_ = f.attackerJar

	rec := f.do(t, http.MethodGet, attackerLoginURL, "", nil)

	if code := mustCodeIfPresent(rec.Header().Get("Location")); code != "" {
		t.Fatalf("a browser that never started this flow completed it: GET %s answered %d "+
			"carrying an authorization code to %s. The victim's session signed an "+
			"authorization request whose client, secret, PKCE verifier and redirect_uri "+
			"all belong to whoever sent them this link",
			attackerLoginURL, rec.Code, oidcTestRedirect)
	}
	if strings.Contains(rec.Header().Get("Location"), oidcTestRedirect) {
		t.Fatalf("the victim's browser was handed to the attacker's redirect_uri: %s",
			rec.Header().Get("Location"))
	}

	switch {
	case rec.Code == http.StatusForbidden:
		// The expected answer, and the one the flow cookie buys.
	case rec.Code == http.StatusFound:
		redirect := mustRedirectToLoginUI(t, rec)
		if redirect.Query().Get(oidc.LoginParamRequestID) != requestIDOf(t, attackerLoginURL) {
			t.Errorf("the redirect names %q rather than the request in the URL; a login UI "+
				"that posts back the wrong id would complete a different request",
				redirect.Query().Get(oidc.LoginParamRequestID))
		}
	default:
		t.Errorf("the victim's browser got %d, want 403 or a redirect to the login UI; "+
			"body:\n%s", rec.Code, rec.Body)
	}
}

// mustCodeIfPresent reads a `code` out of a Location header, or "" when there is
// not one. It does NOT fatal on an unparseable URL, because "there is no code" is
// the answer this whole file is looking for.
func mustCodeIfPresent(location string) string {
	if location == "" {
		return ""
	}
	parsed, err := url.Parse(location)
	if err != nil {
		return ""
	}
	return parsed.Query().Get("code")
}

// signInASecondUser registers and signs in a user who is NOT the fixture's owner,
// and returns their session token.
//
// It exists so the end-to-end case below can tell the two parties apart. A test
// where the attacker's client and the victim's session belong to the same person
// proves the request was completed without a binding; only a test where they are
// DIFFERENT people proves the attacker ends up holding somebody else's tokens.
func (f *oidcFixture) signInASecondUser(t *testing.T) (email string, token string) {
	t.Helper()

	email = uniqueEmailForFlowTest(t)

	rec := f.do(t, http.MethodPost, "/v1/users",
		`{"email":"`+email+`","password":"`+oidcTestPassword+`"}`, nil)
	if rec.Code != http.StatusCreated {
		t.Fatalf("registering the second user: %d; body: %s", rec.Code, rec.Body)
	}

	login := f.do(t, http.MethodPost, "/v1/session",
		`{"email":"`+email+`","password":"`+oidcTestPassword+`"}`, nil)
	if login.Code != http.StatusOK {
		t.Fatalf("signing the second user in: %d; body: %s", login.Code, login.Body)
	}

	var session sessionResponse
	mustJSON(t, login.Body.Bytes(), &session)
	if session.Token == "" {
		t.Fatal("the second user's login carried no session token")
	}
	return email, session.Token
}

// uniqueEmailForFlowTest is dbtest.UniqueEmail, aliased so this file states that
// the address it registers is unique to this run rather than shared with the
// fixture's own registrations.
func uniqueEmailForFlowTest(t *testing.T) string { return dbtest.UniqueEmail(t) }

// RED PROOF — the whole attack, end to end, with two different people in it.
//
// THE TWO PARTIES.
//
//	attacker  the fixture's owner: they own an account, so they registered the
//	          client, they hold its secret, and they chose the PKCE verifier and
//	          the redirect_uri. They start the flow from an unauthenticated
//	          browser and are never signed in themselves.
//	victim    a second, unrelated user. They have a live session and nothing
//	          else; they never asked for this flow and never saw its login page.
//
// WHAT HAPPENS. The victim's browser is navigated to the attacker's login URL —
// a link, an <img>, anything that issues a top-level GET. The service completes
// the request on the strength of the session cookie alone and redirects to the
// attacker's redirect_uri with a code. The attacker exchanges that code with
// their own secret and their own verifier and receives tokens whose subject is
// the VICTIM.
//
// NO SECRET IS PRINTED. The failure message names the subject claim, which is a
// uuid this test generated, and no token, code or secret is ever rendered.
func TestAnAttackerExchangesACodeTheVictimsBrowserMintedForThem(t *testing.T) {
	t.Parallel()

	f := &oidcFlowBindingFixture{oidcFixture: newOIDCFixture(t), attackerJar: &cookieJar{}}

	// The attacker: the fixture's owner, who can therefore register a client.
	attackerClient := f.registerClient(t)
	attackerID := f.owner

	// The attacker starts the flow and keeps the verifier. No session involved.
	verifier, challenge := codeVerifier(t)
	loginURL := f.authorizeAnonymous(t, attackerClient, challenge, "state-attacker", "nonce-attacker")

	// The victim: a different user, signed in, holding only a session cookie.
	_, victimSession := f.signInASecondUser(t)

	jar := &cookieJar{}
	jar.set(victimSession)

	req := newRequestNoCookie(http.MethodGet, loginURL)
	req.Header.Set("Cookie", jar.header())
	rec := newResponse(serveRecorder(f.handler, req))

	code := mustCodeIfPresent(rec.Header().Get("Location"))

	// THE ATTACK IS REFUSED, and a refusal is a PASS rather than a skip. A skip
	// here would report "I could not demonstrate the bug" on exactly the code
	// where the bug is fixed, which is the same false negative in the other
	// direction: the suite would go quiet at the moment it should be loudest.
	// So the two answers are asserted, and only one of them is a failure.
	if code == "" {
		if rec.Code != http.StatusForbidden {
			t.Errorf("the victim's browser was refused with %d, want 403 — a refusal is the "+
				"right answer but an unexplained one, and this file asserts the status so a "+
				"future change cannot quietly turn it into something else", rec.Code)
		}
		return
	}

	// A code WAS minted on the victim's session for the attacker's client. The
	// rest of the exchange is here so the failure names the consequence rather
	// than the mechanism — a code alone might be argued about, a token for the
	// wrong user cannot be.
	tokens := f.exchange(t, attackerClient, code, verifier, oidcTestRedirect)
	if tokens.Code != http.StatusOK {
		t.Fatalf("the victim's browser minted a code for the attacker's client, and the "+
			"attacker then could not redeem it: %d; body: %s", tokens.Code, tokens.Body)
	}

	idToken, _ := tokens.JSON["id_token"].(string)
	if idToken == "" {
		t.Fatal("the token response carried no id_token")
	}

	claims := f.verify(t, idToken)
	sub, _ := claims["sub"].(string)
	if sub == attackerID.String() {
		t.Fatalf("sub = the attacker; the victim contributed nothing to this token, so the " +
			"browser binding is not what this test was checking")
	}

	t.Fatalf("the attack completed: a browser holding only the VICTIM's session minted an "+
		"authorization code for the ATTACKER's client, and the attacker exchanged it for an "+
		"id_token whose subject is %s — a user who never started this flow, never saw its "+
		"login page and never typed a password for it. The attacker now holds the victim's "+
		"identity at a relying party they registered themselves", sub)
}
